### Problem Statement

#### use bagging classifier and regressor, extra tree classifier and regressor, voting classifier and regressor and random forest classifier and regressor on top of Household consumption data and census data

#### Regression for power consumption 

Dataset: https://archive.ics.uci.edu/ml/datasets/census+income

For EDA an FE Please watch this post: https://www.linkedin.com/posts/murali-divya-teja-gummadidala-machine-learning_logisticsvm-assignment-activity-6993985726476378112-XTwa?utm_source=share&utm_medium=member_desktop

**Build the Regression Model for Power consumption using RandomRegressor,Bagggingregressor,Votigregressor**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv(r'C:\Users\HP\Documents\ML-Assignment\ML-assingment\Regression\Household_FE.csv')
df.head()

Global_active_power  Global_reactive_power  Voltage  Sub_metering_1  \
0             0.197943               0.049246   239.13            -0.0   
1             0.240113              -0.000000   245.87            -0.0   
2             0.435888               0.139043   241.34            -0.0   
3             0.188924               0.095637   242.79            -0.0   
4             0.252441               0.074875   242.65            -0.0   

   Sub_metering_2  Sub_metering_3  Year  Month  Day  Hours  Minute  \
0        -0.00000       -0.000000  2007     10   15     23      57   
1        -0.00000        0.598538  2010      2   11      3      27   
2         0.41599       -0.000000  2008      5   25     17       3   
3        -0.00000        0.598538  2009      8    9     11      59   
4        -0.00000       -0.000000  2008      2   19     22      53   

   Total_metering  Energy_minute  
0       -0.000000       4.133333  
1        0.632205       4.300000  
2        0.950787      11.100000  
3        0.632205       2.900000  
4       -0.000000       5.666667

In [4]:
df.columns

Index(['Global_active_power', 'Global_reactive_power', 'Voltage',
       'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3', 'Year', 'Month',
       'Day', 'Hours', 'Minute', 'Total_metering', 'Energy_minute'],
      dtype='object')

### Splitting the Data

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X = df.drop(['Energy_minute'],axis=1)
X.columns

Index(['Global_active_power', 'Global_reactive_power', 'Voltage',
       'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3', 'Year', 'Month',
       'Day', 'Hours', 'Minute', 'Total_metering'],
      dtype='object')

In [7]:
y = df['Energy_minute']
y.head()

0     4.133333
1     4.300000
2    11.100000
3     2.900000
4     5.666667
Name: Energy_minute, dtype: float64

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [10]:
X_train.head()

Global_active_power  Global_reactive_power  Voltage  Sub_metering_1  \
23990             0.167505               0.077479   236.26            -0.0   
8729              0.233211              -0.000000   239.62            -0.0   
3451              0.615852               0.114589   242.61            -0.0   
2628              0.190225              -0.000000   241.53            -0.0   
38352             0.625605              -0.000000   235.47            -0.0   

       Sub_metering_2  Sub_metering_3  Year  Month  Day  Hours  Minute  \
23990       -0.000000       -0.000000  2007      4   27      6      12   
8729        -0.000000        0.598538  2009      4   23     12      33   
3451         0.356905        1.675643  2010      9   18     20      42   
2628        -0.000000       -0.000000  2008      2   10      4      28   
38352       -0.000000        1.646295  2008     12    2      9      58   

       Total_metering  
23990       -0.000000  
8729         0.632205  
3451         2.076484  
2628        -0.000000  
38352        2.007244

In [11]:
X_train.shape

(33500, 12)

In [12]:
y_train.shape

(33500,)

### Regression using RandomRegressor

In [13]:
from sklearn.ensemble import RandomForestRegressor

In [37]:
rdreg = RandomForestRegressor(max_depth=5,random_state=1)

In [38]:
rdreg.fit(X_train,y_train)

RandomForestRegressor(max_depth=5, random_state=1)

In [39]:
y_prd_rd = rdreg.predict(X_test)
y_prd_rd

array([ 5.96939255,  6.24563803,  5.96939255, ...,  3.8565289 ,
        4.64855534, 30.52885764])

In [40]:
rdreg.score(X_train,y_train)

0.9465757363146262

In [41]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [42]:
print(mean_squared_error(y_test,y_prd_rd))
print(mean_absolute_error(y_test,y_prd_rd))
print(np.sqrt(mean_squared_error(y_test,y_prd_rd)))

5.145153639983351
1.1544649295113814
2.2682931115672313


In [43]:
from sklearn.metrics import r2_score

In [44]:
score = r2_score(y_test,y_prd_rd)
print(score)

0.9428052344057696


In [45]:
## Adjusted R2 need to write
adjR = 1 - ( 1-score ) * ( len(y) - 1 ) / ( len(y) - X.shape[1] - 1 )
print(adjR)

0.9427915040921454


#### If we observed the the r2_score has 0.94 and the score can be imporved using the Hyperparameter Tuening as my system is old and i will submit later 

#### Regression using ExtraRegressor

In [33]:
from sklearn.ensemble import ExtraTreesRegressor

In [46]:
extreg = ExtraTreesRegressor(max_depth=5,random_state=1)

In [47]:
extreg.fit(X_train,y_train)

ExtraTreesRegressor(max_depth=5, random_state=1)

In [48]:
extreg.score(X_train,y_train)

0.8514024308428306

In [49]:
y_prd_et = extreg.predict(X_test)
y_prd_et

array([ 5.53279585,  5.86807405,  5.20431563, ...,  3.99488142,
        4.8707353 , 23.74125709])

In [50]:
print(mean_squared_error(y_test,y_prd_et))
print(mean_absolute_error(y_test,y_prd_et))
print(np.sqrt(mean_squared_error(y_test,y_prd_et)))

13.565704366953845
1.8919552410879803
3.6831649931755495


In [51]:
score = r2_score(y_test,y_prd_et)
print(score)

0.8492003668541442


In [52]:
## Adjusted R2 need to write
adjR = 1 - ( 1-score ) * ( len(y) - 1 ) / ( len(y) - X.shape[1] - 1 )
print(adjR)

0.849164165529845


#### If we observed the the r2_score has 0.84 for Extratreeregressor and the score can be imporved using the Hyperparameter Tuening as my system is old and i will submit later.

#### Regression using the VotigRegressor

In [53]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import VotingRegressor

In [55]:
lr1 = LinearRegression()
rreg = RandomForestRegressor(max_depth=5,random_state=1)
kreg = KNeighborsRegressor()

In [56]:
vreg = VotingRegressor([('lr', lr1), ('rf', rreg), ('r3', kreg)])

In [57]:
vreg.fit(X_train,y_train)

VotingRegressor(estimators=[('lr', LinearRegression()),
                            ('rf',
                             RandomForestRegressor(max_depth=5,
                                                   random_state=1)),
                            ('r3', KNeighborsRegressor())])

In [58]:
vreg.score(X_train,y_train)

0.8432573540282888

In [59]:
y_prd_v = vreg.predict(X_test)
y_prd_v

array([ 5.90936735,  7.35070782,  5.65704791, ...,  4.13316489,
        6.26308218, 19.3988025 ])

In [60]:
print(mean_squared_error(y_test,y_prd_v))
print(mean_absolute_error(y_test,y_prd_v))
print(np.sqrt(mean_squared_error(y_test,y_prd_v)))

17.939653295338054
2.4366444697498766
4.235522788905527


In [61]:
score = r2_score(y_test,y_prd_v)
print(score)

0.8005784983571561


In [62]:
## Adjusted R2 need to write
adjR = 1 - ( 1-score ) * ( len(y) - 1 ) / ( len(y) - X.shape[1] - 1 )
print(adjR)

0.8005306247496239


#### If we observed the the r2_score has 0.80 for VotingRegressor and the score can be imporved using the Hyperparameter Tuening as my system is old and i will submit later.

### Regressor using Bagging Regressor

In [63]:
from sklearn.svm import SVR
from sklearn.ensemble import BaggingRegressor


In [64]:
bregr = BaggingRegressor(base_estimator=SVR(),
                        n_estimators=10, random_state=0).fit(X_train, y_train)

In [ ]:
bregr.score(X_train,y_train)